AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Next.js React app hosted on Amplify
#################### PARAMETERS #############################

Parameters:

  Namespace:
    Description: Namespace used as suffix for stack resources
    Type: String

  PageName:
    Description: Name of single page app
    Type: String

  AmplifyFrontendRepository:
    Type: String
    Description: 'Amplify Frontend Repository in the format: https://<GitProviderDomain>/<user>/<repository>'
    Default: 'https://github.com/FundThatFlip/shell-spa-template'


########################### RESOURCES ################################
Resources:

  #################################################################
  # AMPLIFY

  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      # RoleName: !Sub '${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess-Amplify"

  AmplifySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      GenerateSecretString:
        GenerateStringKey: password
        SecretStringTemplate: '{"username":"username"}'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name:
        !Sub '${PageName}-${Namespace}'
      Description: Matching Tool
      EnvironmentVariables:
        - Name: FTF_PAT
          Value: '{{resolve:secretsmanager:aws-amplify-ftf-pat:SecretString:token::}}'
      AutoBranchCreationConfig:
        AutoBranchCreationPatterns:
          - 'feature*/'
        BasicAuthConfig:
          EnableBasicAuth: true
          Password: !Join [ "", [ "{{resolve:secretsmanager:", !Ref AmplifySecret, ":SecretString:password::}}" ] ]
          Username: ftfuser
        EnableAutoBranchCreation: true
        EnableAutoBuild: true
        EnablePullRequestPreview: true
      BasicAuthConfig:
        EnableBasicAuth: false
      BuildSpec: |
        version: "1.0"    
        frontend:
          phases:
            preBuild:
              commands:
                - yarn
            build:
              commands:
                - yarn build
          artifacts:
            baseDirectory: .next
            files:
              - "**/*"
          cache:
            paths:
              - node_modules/**/*
      EnableBranchAutoDeletion: true
      CustomRules:
        - Source: '</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>'
          Target: '/index.html'
          Status: '200'
        - Source: '/<*>'
          Target: '/index.html'
          Status: '404'
      Repository: !Ref AmplifyFrontendRepository
      AccessToken: '{{resolve:secretsmanager:aws-amplify-github:SecretString:token::}}'
      IAMServiceRole: !GetAtt AmplifyRole.Arn

  MainBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      Description: "Main Branch"
      EnableAutoBuild: true
      EnablePullRequestPreview: true

# OUTPUTS #################################################################
